{% set name = "locustio" %}
{% set version = "0.999" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0de762aec06c16f47339d781939a1015f74cf126ee58930b784072c465ab0783

build:
  number: 0
  noarch: python
  entry_points:
    - locust = locust.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - configargparse >=0.15.1
    - flask >=0.10.1
    - gevent >=1.5
    - geventhttpclient >=1.3.1
    - msgpack-python >=0.4.2
    - python
    - pyzmq >=16.0.2
    - requests >=2.9.1
    - six >=1.10.0

test:
  imports:
    - locust
    - locust.contrib
  commands:
    - locust --help

about:
  home: https://locust.io/
  summary: Website load testing framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
