{% set name = "locustio" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: locustio-{{ version }}.tar.gz
  url: https://github.com/locustio/locust/archive/{{ version }}.tar.gz
  sha256: 7a92f0a3adbc838ed3920ac46f57b9a6176663b1c04ea97981e4da8638fec7c6

build:
  number: 0
  noarch: python
  entry_points:
    - locust = locust.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - configargparse >=0.15.1
    - flask >=0.10.1
    - flask-basicauth
    - gevent >=1.5
    - geventhttpclient >=1.3.1
    - msgpack-python >=0.4.2
    - psutil
    - python >=3.6
    - pyzmq >=16.0.2
    - requests >=2.9.1
    - six >=1.10.0

test:
  imports:
    - locust
    - locust.contrib
  commands:
    - locust --help

about:
  home: https://locust.io/
  summary: Website load testing framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
